jobmatch/src/main/java/com/jobmatch/models/RankedSkill.java
package com.jobmatch.models;

import com.jobmatch.repositories.SkillRepository;

import javax.persistence.*;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import java.io.Serializable;
import java.util.*;

@Entity
public class RankedSkill implements RankedIdentifiable, Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected int id;

    @OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.PERSIST)
    @JoinColumn(nullable = false)
    protected Skill skill;

    @Min(0)
    @Max(10)
    protected int rank;

    public RankedSkill() {
    }

    public RankedSkill(Skill skill, int rank) {
        this.skill = skill;
        this.rank = rank;
    }

    public int getId() {
        return id;
    }

    public Skill getSkill() {
        return skill;
    }

    public void setSkill(Skill skill) {
        this.skill = skill;
    }

    public int getRank() {
        return rank;
    }

    public void setRank(int rank) {
        this.rank = rank;
    }

    @Override
    public int getRankedId() {
        return skill.getId();
    }

    @Override
    public String getRankedName() {
        return skill.getName();
    }

    public static void updateSkillSet(String[] skills, String[] ranks, Set<RankedSkill> skillSet, SkillRepository skillRepository) {
        skillSet.clear();
        for (int i = 0; i < skills.length; i++) {
            String s = skills[i];
            if (!s.isEmpty()) {
                Skill skill = skillRepository.findOne(Integer.valueOf(s));
                RankedSkill rankedSkill = new RankedSkill(skill, Integer.valueOf(ranks[i]));
                skillSet.add(rankedSkill);
            }
        }
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        RankedSkill that = (RankedSkill) o;

        if (rank != that.rank) return false;
        return skill != null ? skill.equals(that.skill) : that.skill == null;

    }

    @Override
    public int hashCode() {
        int result = skill != null ? skill.hashCode() : 0;
        result = 31 * result + rank;
        return result;
    }

    @Override
    public String toString() {
        return "RankedSkill{" +
                "id=" + id +
                ", skill=" + skill +
                ", rank=" + rank +
                '}';
    }
}

jobmatch/src/main/java/com/jobmatch/controllers/BaseController.java
package com.jobmatch.controllers;

import com.jobmatch.models.Role;
import com.jobmatch.models.User;
import com.jobmatch.repositories.*;
import com.jobmatch.services.UserRepositoryUserDetails;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.servlet.View;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;
import org.springframework.web.servlet.view.RedirectView;
import org.springframework.web.servlet.view.freemarker.FreeMarkerViewResolver;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import java.util.Locale;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;


@Controller
public class BaseController extends WebMvcConfigurerAdapter {
    protected static final Logger log = LoggerFactory.getLogger(BaseController.class);
    @Autowired
    protected UserRepository userRepository;
    @Autowired
    protected CompanyRepository companyRepository;
    @Autowired
    protected ContactRepository contactRepository;
    @Autowired
    protected RoleRepository roleRepository;
    @Autowired
    protected SkillRepository skillRepository;
    @Autowired
    protected ReferenceRepository referenceRepository;

    @Autowired
    protected CultureRepository cultureRepository;
    @Autowired
    protected EducationRepository educationRepository;
    @Autowired
    protected JobPostRepository jobPostRepository;

    @Autowired
    protected RankedSkillRepository rankedSkillRepository;

    @Autowired
    protected FreeMarkerViewResolver viewResolver;
    @Autowired
    protected HttpServletRequest context;
    @Autowired
    protected HttpSession session;

    static View getRedirectView(String url) {
        RedirectView redirect = new RedirectView(url);
        redirect.setExposeModelAttributes(false);
        return redirect;
    }

    protected View getView(String viewName) {
        try {
            return viewResolver.resolveViewName(viewName, Locale.getDefault());
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }


    @ModelAttribute
    public void addToModel(Model model) {

        model.addAttribute("auth", getAuth());
        model.addAttribute("currentUser", getCurrentUser());
        if (getCurrentUser() != null) {
            model.addAttribute("faves", StreamSupport.stream(getCurrentUser().getFavePosts().spliterator(), false)
                    .map(jobPost -> String.valueOf(jobPost.getId())).collect(Collectors.toList()));
        }
    }


    public Authentication getAuth() {
        return SecurityContextHolder.getContext().getAuthentication();
    }

    public User getCurrentUser() {
        Object principal = getAuth().getPrincipal();
        if (principal instanceof UserRepositoryUserDetails)
            return userRepository.findOne(((UserRepositoryUserDetails) principal).getUser().getId());
        else
            return null;
    }


    protected void enforceSameUserUnlessAdmin(@ModelAttribute User user) {
        User currentUser = getCurrentUser();

        switch (currentUser.getRole().getId()) {
            case Role.SEEKER:
            case Role.EMPLOYER:
                if (currentUser.getId() != user.getId())
                    throw new HttpClientErrorException(HttpStatus.FORBIDDEN);
        }
    }
    protected void enforceSameUserUnlessAdmin(int userId) {
        enforceSameUserUnlessAdmin(userRepository.findOne(userId));
    }

    protected void enforceSameUserOrEmployer(@ModelAttribute User user) {
        User currentUser = getCurrentUser();

        switch (currentUser.getRole().getId()) {
            case Role.SEEKER:
                if (currentUser.getId() != user.getId())
                    throw new HttpClientErrorException(HttpStatus.FORBIDDEN);
        }
    }
    protected void enforceSameUserOrEmployer(int userId) {
        enforceSameUserOrEmployer(userRepository.findOne(userId));
    }
}

jobmatch/src/main/java/com/jobmatch/controllers/SeedController.java
package com.jobmatch.controllers;

import com.github.javafaker.Faker;
import com.jobmatch.models.Contact;
import com.jobmatch.models.User;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

import java.util.Map;

@Controller
public class SeedController extends BaseController {

    /**
     * Creates a new user in the database using random attributes
     */

    @RequestMapping("/seed")
    public String seedDatabase(Map<String, Object> model) {
        model.put("title", "Database Seeder");

        Faker faker = new Faker();

        Contact contact = new Contact(
                faker.phoneNumber().phoneNumber(),
                faker.address().streetAddress(false),
                faker.address().zipCode(),
                faker.internet().url(),
                faker.name().firstName(),
                faker.name().lastName()
        );

        User user = new User(roleRepository.findByName("seeker"), faker.name().name().replace(" ", ""), "myPassword", true, faker.internet().emailAddress());
        user.setContact(contact);
        userRepository.save(user);

        model.put("user", user);

        return "seed";
    }
}

jobmatch/src/main/resources/templates/auth-base.ftl
<#include "base.ftl">

<#macro auth_page_body >
    oops, you forgot to implement an auth_page_body in your template!
</#macro>

<#macro page_head>
<link rel="stylesheet" href="/static/styles/login.css">
</#macro>

<#macro page_body>
<div class="site-container">
    <div class="grid-container">
        <h1><span class="logo"><a href="/">JobMatch</a></span> <@header/></h1>
        <hr>
        <@error_list errors/>
        <@auth_page_body/>
    </div>
</div>
</#macro>

<#macro page_body_footer>
<script type="text/javascript" src="/static/js/paged.js"></script>
</#macro>

jobmatch/src/main/resources/templates/base.ftl
<#import "/spring.ftl" as spring/>
<#assign s=JspTaglibs["/META-INF/spring.tld"] />

<#include "macros.ftl" />

<#macro page_head>

</#macro>

<#macro error_list errors=[]>
	<#if errors??>
		<#list errors as error>
		<li>${error}</li>
		</#list>
	</#if>
</#macro>

<#macro page_body>
	<@error_list errors/>
<h1>Basic Page</h1>
<p>This is the body of the page!</p>
</#macro>


<#macro display_page>
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>${title}</title>
	<!-- Disable tap highlight on IE -->
	<meta name="msapplication-tap-highlight" content="no">

	<!-- Add to homescreen for Chrome on Android -->
	<meta name="mobile-web-app-capable" content="yes">
	<meta name="application-name" content="JobMatch">
	<link rel="icon" sizes="192x192" href="/static/styles/images/touch/chrome-touch-icon-192x192.png">

	<!-- Add to homescreen for Safari on iOS -->
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<meta name="apple-mobile-web-app-title" content="Web Starter Kit">
	<link rel="apple-touch-icon" href="/static/styles/images/touch/apple-touch-icon.png">

	<!-- Tile icon for Win8 (144x144 + tile color) -->
	<meta name="msapplication-TileImage" content="/static/styles/images/touch/ms-touch-icon-144x144-precomposed.png">
	<meta name="msapplication-TileColor" content="#2F3BA2">

	<!-- Color the status bar on mobile devices -->
	<meta name="theme-color" content="#2F3BA2">

	<!-- SEO: If your mobile URL is different from the desktop URL, add a canonical link to the desktop page https://developers.google.com/webmasters/smartphone-sites/feature-phones -->
	<!--
	<link rel="canonical" href="http://www.example.com/">
	-->

	<!--TODO download local copy of remote files -->

    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
    <link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons">
	<link href="/static/styles/jquery-ui.min.css" rel="stylesheet" type="text/css">
	<link href="/static/styles/jquery-ui.structure.min.css" rel="stylesheet" type="text/css">
	<link href="/static/styles/jquery-ui.theme.min.css" rel="stylesheet" type="text/css">
	<link href="/static/styles/material.min.css" rel="stylesheet" type="text/css">
	<link href="/static/styles/getmdl-select.min.css" rel="stylesheet" type="text/css">
	<link href="/static/styles/main.css" rel="stylesheet" type="text/css">

    <script type="text/javascript" src="/static/js/jquery-2.2.0.min.js"></script>
    <script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<@page_head/>
	<script>
		window.FAVE_URL = '${s.mvcUrl("JC#setFavorite").build()}';
		window.CSRF = '${_csrf.token}';

	</script>
</head>
<body>
	<@page_body/>

	<#-- These scripts depend on DOM elements and should be loaded after those elements are added to the DOM. -->
<script type="text/javascript" src="/static/js/material.min.js"></script>
<script type="text/javascript" src="/static/js/getmdl-select.min.js"></script>
<script type="text/javascript" src="/static/js/main.js"></script>
<!-- footer scripts -->
	<@page_body_footer/>
</body>
</html>
</#macro>

<#macro page_body_footer>

</#macro>

jobmatch/src/main/resources/templates/dashboard-base.ftl
<#include "base.ftl">


<#macro page_head>
<link rel="stylesheet" href="/static/styles/main.css">
</#macro>
<#macro dashoard_body>
You forgot to include the dashboard body
</#macro>
<#macro page_body>
<div id="wrapper">
    <header>
        <h4 class="headline"><a href="/" class="logo-link"><span class="logo">JobMatch</span> | <span
                class="role-name">${currentUser.role.name}</span></a></h4>
    </header>

    <div id="sidebar">
        <div style="text-align:center;">
            <#if currentUser.contact?? && ( currentUser.contact.firstName?has_content || currentUser.contact.lastName?has_content)>
                <h5 class="company">${currentUser.contact.firstName} ${currentUser.contact.lastName}</h5>
            <#else>
                <h5 class="company">${currentUser.username}</h5>
            </#if>
        </div>
        <br>

        <#switch currentUser.role.name>
            <#case "Admin">

                <#break>
            <#case "Seeker">

                <#break>
            <#case "Employer">
                <a class="sidebar-button" href="${s.mvcUrl("JC#createJob").build()}">+ post a job</a>
                <#break>
            <#default>

                Unknown role [${currentUser.role.name}]
                <#break>
        </#switch>


        <br>

        <nav>
            <ul id="sidebar-nav">
                <li><a href="${s.mvcUrl("JC#listJobs").build()}">Jobs</a></li>
                <li><a href="${s.mvcUrl("UC#getProfile").arg(0,currentUser.id).build()}">Profile</a></li>

                <#switch currentUser.role.name>
                    <#case "Admin">

                        <#break>
                    <#case "Seeker">
                        <li>
                            <a href="${s.mvcUrl("UQC#getQualifications").arg(0,currentUser.id).build()}#tblQualifications">Qualifications</a>
                        </li>
                        <li>
                            <a href="${s.mvcUrl("EC#viewEducation").arg(0, currentUser.id).build()}">Education</a>
                        </li>
                        <li>
                            <a href="${s.mvcUrl("RC#viewReference").arg(0,currentUser.id).build()}#tblReferences">References</a>
                        </li>
                        <li><a href="${s.mvcUrl("JC#listFavoriteJobPosts").arg(0,currentUser.id).build()}">Favorites</a>
                        </li>
                        <#break>
                    <#case "Employer">
                        <li><a href="${s.mvcUrl("CC#getCompany").arg(0,currentUser.company.id).build()}">My company</a>
                        </li>
                        <#break>
                    <#default>

                        Unknown role ${currentUser.role.name}
                        <#break>
                </#switch>
                <li><a href="/logout">Logout</a></li>
            </ul>
        </nav>
    </div>

    <section id="content"><@dashboard_body /></section>

    <div class="clear"></div>
</div>
</#macro>

<#macro page_body_footer>
<script type="text/javascript" src="/static/js/paged.js"></script>
</#macro>

jobmatch/src/main/resources/templates/index.ftl
<#include "auth-base.ftl">

<#macro header>LOGIN</#macro>

<#macro auth_page_body>
<form action="/login" name="user" method="post" class="form form-login">
    <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" id="login-username" name="username" required autofocus>
        <label class="mdl-textfield__label" for="login-username">Username</label>
    </div>
    <br/>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="password" id="login-password" name="password" required>
        <label class="mdl-textfield__label" for="login-password">Password</label>
    </div>

    <a href="#" class="mdl-button mdl-js-button mdl-js-ripple-effect">Forgot...</a>
    <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored white-font-button">
        Login
    </button>
</form>

<div class="form-text">
    <p>
        <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored white-font-button"
                onclick="parent.location='/register'">Register
        </button>
    </p>
</div>
</#macro>
<@display_page/>

jobmatch/src/main/resources/templates/macros.ftl
<#macro rankedChoiceList fieldName availableChoices, chosenChoices>

    <#assign i = 0 />
    <ul class="checkbox-list">
        <#list availableChoices?keys as choice>
            <li>

                <label for="${fieldName}-${i}" class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect">
                    <input id="${fieldName}-${i}" type="checkbox" name="${fieldName}" value="${choice}"
                           class="mdl-checkbox__input"
                           <#if chosenChoices?? && chosenChoices.contains(choice)>checked</#if>/>
                    <span class="mdl-checkbox__label">${availableChoices[choice]}</span>
                </label>

                <input type="hidden" class="rank" name="${fieldName}Ranks" data-choice="${choice}"
                       value="<#if chosenChoices?? && chosenChoices.contains(choice)>${chosenChoices.getRank(choice)}</#if>"/>
            </li>
            <#assign i = i + 1 />
        </#list>
    </ul>

    <ol id="${fieldName}-sort" class="sortable-list" data-field="${fieldName}">
        <#list chosenChoices.sortedRankables as choice>
            <li class="skill-culture-item" data-choice="${choice.rankedId}">
            ${choice.rankedName}
            </li>
        </#list>
    </ol>


</#macro>

jobmatch/src/main/resources/templates/paged-dashboard-base.ftl
<#include "dashboard-base.ftl">

<#macro paged_dashboard_page_body >
oops, you forgot to implement an paged_dashboard_page_body in your template!
</#macro>

<#macro form_attributes ></form>oops, you forgot the form attributes in your template!</#macro>


<#macro dashboard_body>
<div class="mdl-grid">
    <div class="mdl-cell--4-offset-desktop mdl-cell--2-offset-tablet mdl-cell mdl-cell--4-col">
        <@error_list errors/>
    </div>
    <div class="mdl-cell mdl-cell--3-offset-desktop mdl-cell--6-col-desktop mdl-cell--8-col-tablet">
        <div class="mdl-card-wide mdl-card mdl-shadow--2dp">
            <div class="mdl-card__title mdl-card--expand">
                <h2 class="mdl-card__title-text">Edit Profile</h2>
            </div>
            <div class="mdl-card__supporting-text">
                <form <@form_attributes/> class="form form-profile js-page-container">

                    <@spring.bind "user" />
                    <@spring.showErrors '*', 'errors' />

                    <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>

                    <div id="progress"></div>


                    <@paged_dashboard_page_body/>
            </div>
            <div class="mdl-card__actions mdl-card--border mdl-typography--text-center">
                <button id="back" type="button" class="mdl-button mdl-js-button mdl-js-ripple-effect">
                    &lt; Back
                </button>
                <button id="next" type="button"
                        class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored form-button">
                    Next &gt;
                </button>
                <p><a href="${s.mvcUrl("UC#delete").arg(0,user.id).build()}">Delete My Account</a></p>
            </div>

            </form>
        </div>
    </div>
</div>
</#macro>

jobmatch/src/main/resources/templates/registration.ftl
<#include "auth-base.ftl">

<#macro header>REGISTER</#macro>

<#macro auth_page_body>
<form action="/register" name="user" method="post" class="form form-login">
    <@spring.bind "user" />
    <@spring.showErrors '*', 'errors' />

    <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
    <div class="form-field">
        <label class="demo-list-radio mdl-radio mdl-js-radio mdl-js-ripple-effect" for="role0">
            <input type="radio" id="role0" class="mdl-radio__button" name="role" value="2" checked/> Seeker
        </label>
        <br/>
        <label class="demo-list-radio mdl-radio mdl-js-radio mdl-js-ripple-effect" for="role1">
            <input type="radio" id="role1" class="mdl-radio__button" name="role" value="3"/> Employer
        </label>
    </div>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" id="username" name="username" required>
        <label class="mdl-textfield__label" for="username">Username</label>
    </div>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="email" id="email" name="email" required>
        <label class="mdl-textfield__label" for="email">Email</label>
    </div>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="password" id="password" name="password" required>
        <label class="mdl-textfield__label" for="password">Password</label>
    </div>
    <div class="form-field">
        <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="optIn">
            <input type="checkbox" id="optIn" name="optIn" class="mdl-checkbox__input"/> Opt in
        </label>
    </div>
    <a href="/login" class="mdl-button mdl-js-button mdl-js-ripple-effect">&lt; login</a>
    <button type="submit" value="create"
            class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored white-font-button">
        Register
    </button>
</form>


</#macro>
<@display_page/>

jobmatch/src/main/resources/templates/seed.ftl
<#include "base.ftl">


<#macro page_body>
<h1>Seeder</h1>

The following user was added to the database:<br/>
${user.toString()}

</#macro>

<@display_page/>